### ISSUE TITLE
Missing value reported to JMRI

### ISSUE THREAD

**Issue by ggee** [manu-fwi/openlcb-gateway#10]
When I open the node configuration window in JMRI, I see the node information seems not to have been substituted.

![image](https://user-images.githubusercontent.com/4544293/90714049-cc4e7900-e274-11ea-98db-0d5f81fb64ba.png)

**Comment by manu-fwi** [comment]
Fixed in https://github.com/manu-fwi/openlcb-gateway/commit/733ca58eefb52f8cda0770d9a940b71e62389cc0
