### ISSUE TITLE
Configuration not loading into JMRI properly

### ISSUE THREAD

**Issue by ggee** [manu-fwi/openlcb-gateway#5]
Node information in JMRI is invalid.  

![image](https://user-images.githubusercontent.com/4544293/89972175-1f984a00-dc2b-11ea-841e-2d195fd4736c.png)

When trying to 'Open Configuration dialog', nothing appears.

![image](https://user-images.githubusercontent.com/4544293/89972289-730a9800-dc2b-11ea-89a1-140b3cca0483.png)

**Comment by ggee** [comment]
Update 1:  Interesting find.  This problem only occurs if I open JMRI on the RPi.  If I open JMRI on my Windows PC and connect to the gateway, all looks fine.

![image](https://user-images.githubusercontent.com/4544293/89975182-1ad79400-dc33-11ea-8d9a-dd81f564f01a.png)

Update 2:  Well, I crashed the gateway and when I restarted and refreshed the node list, both JMRI show garbled content.

![image](https://user-images.githubusercontent.com/4544293/89975601-28d9e480-dc34-11ea-811d-c7ad404c91d3.png)

**Comment by manu-fwi** [comment]
Do you have the same versions on both?

**Comment by ggee** [comment]
Yes, both have 4.20.

**Comment by ggee** [comment]
This doesn't seem to be specific to RR-duino.  I tried the cmri_net_serial and see the same problem.  When I look at the stdout of the openlcb_gateway.py, it shows this. I don't know the protocol, so I can't tell if it is correct or not.

```
sending poll to cpNode (add= 101 )
new msg= :X19490370N;
event/frame transferred by server =  b':X19490370N;'
event/frame transferred by server =  b':X19170132N020112AAAAAA;'
event/frame transferred by server =  b':X19170132N020112AAAAAA;'
Sent---> :X19170132N020112AAAAAA;
new msg= :X19170370N020112C0177A;
event/frame transferred by server =  b':X19170370N020112C0177A;'
new msg= :X19DE8370N0132;
sent SNIR Reply
data= b'n gate'
data= b'way\x00te'
data= b'st\x001.0'
data= b'\x001.0\x00\x02'
data= b'gw1\x00ga'
data= b'teway-'
data= b'1'
---> b':X19A08132N04707974686F;'
---> b':X19A08132N6E2067617465;'
---> b':X19A08132N776179007465;'
---> b':X19A08132N737400312E30;'
---> b':X19A08132N00312E300002;'
---> b':X19A08132N677731006761;'
---> b':X19A08132N74657761792D;'
---> b':X19A08132N31;'

```

**Comment by manu-fwi** [comment]
Hmm it looks like the last string is always missing the terminal null character.

**Comment by manu-fwi** [comment]
I commited a fix for that, hopefully.

**Comment by ggee** [comment]
I can still reproduce. 

1. gateway, net_serial and JMRI running
2. In JMRI, open Network Tree and Refresh.  All looks good.
3. Open the configuration dialog of a node in JMRI and try and 'Write' a 'Node Name'.
4. This will cause the gateway and net_serial to crash.
5. Do not close JMRI.
6. Restart gateway and net_serial.
7. In JMRI, click the Refresh again.  Node list content should look messed up.

NOTES:
- opening and closing the Network Tree does not clean up.
- restarting JMRI returns the list to a good state.

So not sure if this is a JMRI issue or a sync phase issue.

**Comment by manu-fwi** [comment]
I have a fix for the write that causes a crash but I need some input from the openlcb guys. Stay tuned.

**Comment by manu-fwi** [comment]
OK can you test the latest git, it should be fixed!

**Comment by manu-fwi** [comment]
I think this is fixed now.
